version: '3.8'

services:
    app:
        build: .
        container_name: ordercase-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www

    nginx:
        image: nginx:latest
        container_name: ordercase-nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf

    mysql:
        image: mysql:8.0
        container_name: ordercase-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    redis:
        container_name: ordercase-redis
        image: redis:latest
